//
//  ClipboardMonitor.swift
//  ClipboardManager
//

import Foundation
import AppKit

public final class ClipboardMonitor {
    public static let shared = ClipboardMonitor()

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private var lastWrittenChangeCount: Int = -1

    // Private pasteboard markers used by password managers and security software
    private let privateTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    private init() {
        self.lastChangeCount = pasteboard.changeCount
    }

    public func startMonitoring() {
        stopMonitoring()
        self.lastChangeCount = pasteboard.changeCount
        self.timer = Timer.scheduledTimer(withTimeInterval: 0.35, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // Ignore clipboard changes triggered by our own app writing back
        if currentCount == lastWrittenChangeCount {
            return
        }

        // If monitoring is paused in settings/menu, ignore
        guard !ClipboardStore.shared.isPaused else { return }

        // Check for password manager concealed types
        if let types = pasteboard.types {
            for privType in privateTypes {
                if types.contains(privType) {
                    return
                }
            }
        }

        // Check frontmost app exclusion
        let frontApp = NSWorkspace.shared.frontmostApplication
        let bundleID = frontApp?.bundleIdentifier
        if AppExclusionList.shared.isExcluded(bundleIdentifier: bundleID) {
            return
        }

        let appName = frontApp?.localizedName ?? "Unknown App"

        // Process pasteboard contents
        processPasteboard(sourceBundleId: bundleID, sourceAppName: appName)
    }

    private func processPasteboard(sourceBundleId: String?, sourceAppName: String?) {
        guard let types = pasteboard.types, !types.isEmpty else { return }

        // 1. Check for Finder Files / URLs
        if ClipboardStore.shared.trackFiles {
            if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [
                NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: true
            ]) as? [URL], !fileURLs.isEmpty {
                let paths = fileURLs.map { $0.path }
                let item = ClipboardItem(
                    contentType: .file,
                    filePaths: paths,
                    sourceAppBundleId: sourceBundleId,
                    sourceAppName: sourceAppName,
                    characterCount: paths.joined().count,
                    byteSize: 0
                )
                ClipboardStore.shared.addItem(item)
                SoundManager.shared.playCopySound()
                return
            }
        }

        // 2. Check for Plain Text / Rich Text / URLs / Hex Colors
        // Using NSPasteboard.general.string directly for 100% compatibility across all macOS apps
        if let rawText = pasteboard.string(forType: .string), !rawText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            if ClipboardStore.shared.trackText {
                let trimmed = rawText.trimmingCharacters(in: .whitespacesAndNewlines)
                var contentType: ClipboardContentType = .text

                var rtfData: Data? = nil
                var htmlString: String? = nil
                if ClipboardStore.shared.trackRichText {
                    if types.contains(.rtf) {
                        rtfData = pasteboard.data(forType: .rtf)
                    }
                    if types.contains(.html) {
                        htmlString = pasteboard.string(forType: .html)
                    }
                }

                if (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://")) && !trimmed.contains(" ") {
                    contentType = .url
                } else if (trimmed.hasPrefix("#") && (trimmed.count == 7 || trimmed.count == 9)) ||
                            trimmed.hasPrefix("rgb(") || trimmed.hasPrefix("rgba(") {
                    contentType = .color
                } else if rtfData != nil || htmlString != nil {
                    contentType = .richText
                }

                let item = ClipboardItem(
                    contentType: contentType,
                    plainText: rawText,
                    rtfData: rtfData,
                    htmlContent: htmlString,
                    sourceAppBundleId: sourceBundleId,
                    sourceAppName: sourceAppName,
                    characterCount: rawText.count,
                    byteSize: rawText.utf8.count
                )
                ClipboardStore.shared.addItem(item)
                SoundManager.shared.playCopySound()
                return
            }
        }

        // 3. Check for Images (Only if no string was found, e.g. Lightshot / screenshots / Copy Image)
        if ClipboardStore.shared.trackImages {
            let hasImage = types.contains(.png) || types.contains(.tiff) || types.contains(NSPasteboard.PasteboardType("public.image"))
            if hasImage {
                if let imgData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
                    if let saved = ClipboardStore.shared.saveImagePayload(data: imgData) {
                        let item = ClipboardItem(
                            contentType: .image,
                            imageFileName: saved.fileName,
                            imageWidth: saved.width,
                            imageHeight: saved.height,
                            sourceAppBundleId: sourceBundleId,
                            sourceAppName: sourceAppName,
                            characterCount: 0,
                            byteSize: imgData.count,
                            contentHash: saved.hash
                        )
                        ClipboardStore.shared.addItem(item)
                        SoundManager.shared.playCopySound()
                        return
                    }
                }
            }
        }
    }

    /// Writes an item back to NSPasteboard without triggering duplicate capture
    public func writeItemToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()

        switch item.contentType {
        case .text, .url, .color:
            if let text = item.plainText {
                pasteboard.setString(text, forType: .string)
            }
        case .richText:
            if let rtf = item.rtfData {
                pasteboard.setData(rtf, forType: .rtf)
            }
            if let html = item.htmlContent {
                pasteboard.setString(html, forType: .html)
            }
            if let text = item.plainText {
                pasteboard.setString(text, forType: .string)
            }
        case .image:
            if let imgName = item.imageFileName,
               let image = ClipboardStore.shared.loadImage(named: imgName),
               let tiffData = image.tiffRepresentation {
                pasteboard.setData(tiffData, forType: .tiff)
            }
        case .file:
            if let paths = item.filePaths {
                let urls = paths.map { URL(fileURLWithPath: $0) as NSURL }
                pasteboard.writeObjects(urls)
            }
        }

        // Update changeCounts to prevent re-recording our own write
        lastWrittenChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }
}
